apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo
  type: NodePort # Exposes the service on the VM's IP at a static port
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 4000 
      # NodePort will be assigned automatically from the 30000-32767 range