name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "master" ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Set repo name to lowercase
        run: echo "IMAGE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPO }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_REPO }}:latest

      - name: Update deployment timestamp
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          sed -i "s/last-updated: \"\"/last-updated: \"$(date +%s)\"/" k8s/deployment.yml
          git add k8s/deployment.yml
          git commit -m "ci: Update deployment timestamp to trigger rollout"
          git push